//  MY NAME IS KHAWAJA ASGHAR ALI .WORKING DATE 13/3/2024  ////
//     WE ARE WORKING ON AIRTHMETIC OPERATORS   //
let sum1 = 5;
let num2 = 3;
console.log(5 + 3);
//  MY NAME IS KHAWAJA ASGHAR ALI .WORKING DATE 13/3/2024  ////
//     WE ARE WORKING ON AIRTHMETIC OPERATORS   //
//   HERE WE MADE ADDITION BETWEEN TOW VALUES ,USING VARIALE (NUM1 + NUM2 =8)  //
let num3 = 12;
let num4 = 4;
console.log(12 - 4);
//  MY NAME IS KHAWAJA ASGHAR ALI .WORKING DATE 13/3/2024  ////
//     WE ARE WORKING ON AIRTHMETIC OPERATORS   //
//   HERE WE MADE SUBTRACTION BETWEEN TOW VALUES ,USING VARIALE (NUM1 - NUM2 =8)  //
let num5 = 4;
let num6 = 2;
console.log(4 * 2);
//  MY NAME IS KHAWAJA ASGHAR ALI .WORKING DATE 13/3/2024  ////
//     WE ARE WORKING ON AIRTHMETIC OPERATORS   //
//   HERE WE MADE MULTIPLICATION BETWEEN TOW VALUES ,USING VARIALE (NUM1 * NUM2 =8)  //
let num7 = 16;
let num8 = 2;
console.log(16 / 2);
//  MY NAME IS KHAWAJA ASGHAR ALI .WORKING DATE 13/3/2024  ////
//     WE ARE WORKING ON AIRTHMETIC OPERATORS   //
//   HERE WE DEVIDE BETWEEN TOW VALUES ,USING VARIALE (NUM1 / NUM2 =8)  //
